changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - chore
        - ci
        - refactor
    - title: Other Changes
      labels:
        - "*"
